[project]
name = "jobagent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "pydantic>=2",
    "sqlalchemy",
    "alembic",
    "psycopg[binary]",
    "pgvector",
    "sentence-transformers",
    "structlog",
    "python-dotenv>=1.2.3",
    "jinja2>=3.1.6",
    "anthropic>=1.5.0",
]

[build-system]
requires = ["uv_build>=0.9"]
build-backend = "uv_build"


[dependency-groups]
dev = ["pytest", "pytest-vcr", "ruff", "ipykernel"]
