"""Add trace_id to LLMCall

Revision ID: 8b3e3c21700a
Revises: befeaed19f09
Create Date: 2026-09-12 15:57:12.708828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3e3c21700a'
down_revision: Union[str, Sequence[str], None] = 'befeaed19f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('llm_call', 'LLMCall')
    op.add_column('LLMCall', sa.Column('trace_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LLMCall', 'trace_id')
    # ### end Alembic commands ###
