"""initial schema

Revision ID: befeaed19f09
Revises: 
Create Date: 2026-09-03 23:15:05.961324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'befeaed19f09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('app_user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('ats_type', sa.String(), nullable=True),
    sa.Column('ats_slug', sa.String(), nullable=True),
    sa.Column('careers_url', sa.String(), nullable=True),
    sa.Column('size_bucket', sa.String(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('hq_country', sa.String(), nullable=True),
    sa.Column('is_blocklisted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ats_type', 'ats_slug', name='uq_company_ats'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('llm_call',
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('consent_basis', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offer',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('normalized_title', sa.String(), nullable=False),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('description_raw', sa.String(), nullable=True),
    sa.Column('description_clean', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('remote_policy', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_is_stated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tech_stack', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('repost_count', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('ghost_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_job_offer_source')
    )
    op.create_index('ix_job_offer_summary_embedding_hnsw', 'job_offer', ['summary_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'summary_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_table('profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('seniority', sa.String(), nullable=False),
    sa.Column('target_titles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('hard_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soft_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offer.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requirement',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('requirement_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_requirement_embedding_hnsw', 'job_requirement', ['requirement_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'requirement_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_table('matching',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('stage_reached', sa.SmallInteger(), nullable=True),
    sa.Column('filter_rejections', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_fit_score', sa.SmallInteger(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('scored_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('human_label', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offer.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'profile_id', name='uq_matching_offer_profile')
    )
    op.create_table('document',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('version', sa.SmallInteger(), nullable=True),
    sa.Column('proof_point_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('unanchored_claims', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('approved_by_human', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_point',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('strength', sa.SmallInteger(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proof_point')
    op.drop_table('document')
    op.drop_table('matching')
    op.drop_index('ix_job_requirement_embedding_hnsw', table_name='job_requirement', postgresql_using='hnsw', postgresql_ops={'requirement_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('job_requirement')
    op.drop_table('experience')
    op.drop_table('application')
    op.drop_table('profile')
    op.drop_index('ix_job_offer_summary_embedding_hnsw', table_name='job_offer', postgresql_using='hnsw', postgresql_ops={'summary_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('job_offer')
    op.drop_table('contact')
    op.drop_table('llm_call')
    op.drop_table('company')
    op.drop_table('app_user')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
